language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

env:
  global:
    - secure: "qUxCFouPoRo9a7rmPLiKpjvzZ0AlOxQ+/GhRq/P5MxLpnuFwwUzfBI0Q+vF+DP24tY/qDsXJI5AsWnkygamS+HxqGoZYK7hX5bGeUynN0X+spvgzciiqWso8FoWNp8wHztITtEISHT31IIDsOxfrAtMeHKbTvjtAbs3JDDZdRIM="

services:
  - redis-server

script:
  - mvn package jacoco:report coveralls:jacoco
